package cmd

import (
	"errors"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "finddupe",
	Short: "A fast duplicate file finder and eliminator",
	Long: `finddupe is a fast, cross-platform tool to find and eliminate duplicate files.
It supports:
  - Multi-threaded file scanning for improved performance
  - Cross-platform support (Linux, macOS, Windows)
  - Finding existing hard link groups
  - Finding same files generated by CoW (if FS supports CoW)
  - Deleting duplicate files to save space
  - Creating hard links to eliminate duplicates
  - Creating CoW copies to eliminate duplicates
  - Unicode filename support
  - Long path support

Original C version by Matthias Wandel, Go rewrite with multi-threading support.`,

	// Runtime failures (I/O errors, cancellation) should not dump the full
	// usage text; cobra still reports argument errors.
	SilenceUsage: true,

	// A bare invocation does nothing, so it must not look like a successful run:
	// print the help and report the missing subcommand as a usage error. An
	// unknown argument is reported by cobra itself before this runs.
	RunE: func(cmd *cobra.Command, args []string) error {
		if len(args) == 0 {
			_ = cmd.Help()
			return errors.New("no subcommand given: use 'find' or 'dedupe'")
		}
		return fmt.Errorf("unknown command %q: use 'find' or 'dedupe'", args[0])
	},
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}
