package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "finddupe",
	Short: "A fast duplicate file finder and eliminator",
	Long: `finddupe is a fast, cross-platform tool to find and eliminate duplicate files.
It supports:
  - Multi-threaded file scanning for improved performance
  - Cross-platform support (Linux, macOS, Windows)
  - Finding existing hard link groups
  - Finding same files generated by CoW (if FS supports CoW)
  - Deleting duplicate files to save space
  - Creating hard links to eliminate duplicates
  - Creating CoW copies to eliminate duplicates
  - Unicode filename support
  - Long path support

Original C version by Matthias Wandel, Go rewrite with multi-threading support.`,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}
